#!/bin/bash

docker rm -f $(docker ps -q)

docker run -d --name="postgres" --restart="always" \
-p 127.0.0.1:5432:5432 \
-v /opt/database:/var/lib/postgresql/data \
-v /var/log/postgresql:/var/log/postgresql postgres:9.4

# run aeroo
docker run -d --name="aeroo_docs" --restart="always" bmya/aeroo-docs

docker run -d --name="odoo" --restart="always" \
-v /opt/odoo/extra-addons:/mnt/extra-addons \
-v /opt/odoo/.filestore:/opt/odoo/.filestore \
-v /opt/odoo/conf:/etc/odoo \
--link aeroo_docs:aeroo \
--link postgres:db -t bmya/odoo-bmya:t14 -- -d nombre_bd

docker run -d --name="nginx" --restart="always" \
--link odoo:odoo \
-v /opt/nginx:/etc/nginx/conf.d \
-p 80:80 nginx

docker ps

docker attach odoo
