version: '2'
services:
    web:
        container_name: nginx
        image: nginx
        restart: always
        volumes:
            - ./nconf:/etc/nginx/conf.d
        networks:
            - default
            - odoo8_default
        external_links:
            - odoo:odoo
        ports:
            - "80:80"
            - "443:443"
    aeroo:
       container_name: aeroo_docs
       image: bmya/aeroo-docs
       restart: always
networks:
    default:
        driver: bridge
    odoo8_default:
        external: true

